apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-db
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        appdb: mongo-db
    spec: 
      containers:
      - name: mongo-db
        image: mongo:3.3
        env:
        - name: MONGODB_DATABASE
          value: mongo-data
        ports:
        - containerPort: 27017