---

apiVersion: v1
kind: Namespace
metadata:
  name: n1 

---
# Role in the “authn” namespace that can be used to grant read access to pods:
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: n1 
  name: read
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
# This role binding allows "user01" to have role01 role in the "authn" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding01
  namespace: n1
subjects:
- kind: User
  name: adminsan1 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  namespace: n1 
  name: read
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminsan1
  namespace: n1
#automountServiceAccountToken: false

