apiVersion: v1
kind: Service
metadata:
  name: webserver-nginx-nodeport
  namespace: bdf-credor-poc
  labels:
    run: webserver-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: webserver-nginx 