apiVersion: v1
kind: Namespace
metadata:
  name: n1

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-nginx
  namespace: n1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver-nginx
    spec:
      containers:
      - name: webserver-nginx
        image: nginx:alpine
        env:
        - name: ENV1 
          value: "hello word ENV var"
        ports:
        - containerPort: 80

